# Generated by Django 5.0.7 on 2024-11-06 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
